// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChpV5ZfwV2O0XzxBZh7-PlOj9dEmW6zII',
    appId: '1:997271121553:web:cfddd75a9f9a11cde15930',
    messagingSenderId: '997271121553',
    projectId: 'simple-budget-tracker-1b3df',
    authDomain: 'simple-budget-tracker-1b3df.firebaseapp.com',
    storageBucket: 'simple-budget-tracker-1b3df.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxe5kGCpo7r4_nO0IVF_L0tK0N4ORfdSY',
    appId: '1:997271121553:ios:780708e83c61c898e15930',
    messagingSenderId: '997271121553',
    projectId: 'simple-budget-tracker-1b3df',
    storageBucket: 'simple-budget-tracker-1b3df.appspot.com',
    iosClientId: '997271121553-kjcs20mp7jehs2on3j5ql8poakjgqpfs.apps.googleusercontent.com',
    iosBundleId: 'com.kimapp.budgetTracker',
  );
}
