// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSYdiIqHpua50wmcwmNyENa44MuRLBB78',
    appId: '1:177051866505:web:31ead7bf4260f756fcfd58',
    messagingSenderId: '177051866505',
    projectId: 'hea-srun-money-tracker',
    authDomain: 'hea-srun-money-tracker.firebaseapp.com',
    storageBucket: 'hea-srun-money-tracker.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARR1lkTmHH1QuSlA6GgTvXGigCZahWy28',
    appId: '1:177051866505:ios:d8513e46193c1c52fcfd58',
    messagingSenderId: '177051866505',
    projectId: 'hea-srun-money-tracker',
    storageBucket: 'hea-srun-money-tracker.appspot.com',
    iosClientId: '177051866505-7b9esdchu3enq85p9dfn4fq7inbuajr4.apps.googleusercontent.com',
    iosBundleId: 'com.kimapp.budgetTracker',
  );
}
